# Generated by Django 5.1.1 on 2024-09-30 07:36

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "thumbnail",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="Thumbnail"
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("organizer", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("U", "upcoming"), ("P", "past")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-create_date",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=9, unique=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "profile_picture",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Image"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "past_events",
                    models.ManyToManyField(
                        blank=True, related_name="past_users", to="core.event"
                    ),
                ),
                (
                    "registered_events",
                    models.ManyToManyField(
                        blank=True, related_name="registered_users", to="core.event"
                    ),
                ),
            ],
            options={
                "ordering": ("-create_date",),
            },
        ),
        migrations.CreateModel(
            name="ReservationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "active"), ("C", "cancelled"), ("E", "expired")],
                        default="active",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        default=uuid.uuid4,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.event",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=uuid.uuid4,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-create_date",),
            },
        ),
    ]
